
title: Nate Meier
name: Nate Meier
email: nate@natemeier.com
locale: Longmont, CO
description: Website-maker, geologist, musician, translator.
baseurl: ""
url: "http://natemeier.github.io"
keybase_username:      natemeier
github_username:       natemeier
twitter_username:      iemanatemire
flickr_username:       natemeier
linkedin_username:     natemeier
soundcloud_username:   iemanatemire

markdown: kramdown
