
title: I emanate, mire.
name: Nate Meier
email: iemanatemire@gmail.com
locale: Longmont, CO
description: Website-maker, geologist, musician, translator.
baseurl: ""
url: "http://iemanatemire.github.io"
twitter_username:      iemanatemire
github_username:       iemanatemire
flickr_username:       natemeier
linkedin_username:     natemeier
soundcloud_username:   iemanatemire

markdown: kramdown
