---

title: Nate Meier
name: Nate Meier
email: nate@natemeier.com
locale: Longmont, CO
description: A big nerd.
baseurl: ""
url: http://natemeier.github.io
github_username: natemeier
linkedin_username: natemeier
strava_username: natemeier
goodreads_username: natemeier

markdown: kramdown
