# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I emanate, mire.
name: Nate Meier
email: iemanatemire@gmail.com
description: I work as a web developer in Boulder, CO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iemanatemire.github.io" # the base hostname & protocol for your site
twitter_username:      iemanatemire
github_username:       iemanatemire
flickr_username:       natemeier
linkedin_username:     natemeier
soundcloud_username:   iemanatemire

# Build settings
markdown: kramdown
